// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQyYRqfYEKkqhPSryMvNiJoA_nSaORvp4',
    appId: '1:429756858361:web:c7eab85b068c108efc8728',
    messagingSenderId: '429756858361',
    projectId: 'cspt-survey',
    authDomain: 'cspt-survey.firebaseapp.com',
    storageBucket: 'cspt-survey.appspot.com',
    measurementId: 'G-BW7GKK22LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC27MPg7LmVqUBSvJ96b092tu-50CGE4CU',
    appId: '1:70663231893:android:bc3857a550c391bf41fe9c',
    messagingSenderId: '70663231893',
    projectId: 'cspt-survey-5148c',
    storageBucket: 'cspt-survey-5148c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtOgjd4XfhhiDNO7yjkvtVn47ZmyE4u2s',
    appId: '1:429756858361:ios:2571e2e5ea70c5ecfc8728',
    messagingSenderId: '429756858361',
    projectId: 'cspt-survey',
    storageBucket: 'cspt-survey.appspot.com',
    iosBundleId: 'com.example.cssptApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtOgjd4XfhhiDNO7yjkvtVn47ZmyE4u2s',
    appId: '1:429756858361:ios:2571e2e5ea70c5ecfc8728',
    messagingSenderId: '429756858361',
    projectId: 'cspt-survey',
    storageBucket: 'cspt-survey.appspot.com',
    iosBundleId: 'com.example.cssptApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQyYRqfYEKkqhPSryMvNiJoA_nSaORvp4',
    appId: '1:429756858361:web:c87372c49b9ca9bffc8728',
    messagingSenderId: '429756858361',
    projectId: 'cspt-survey',
    authDomain: 'cspt-survey.firebaseapp.com',
    storageBucket: 'cspt-survey.appspot.com',
    measurementId: 'G-R19HJL8BHH',
  );
}
